---
- name: Installing Mysql  and dependencies
  package:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - mysql-server
    - mysql-client
    - python3-mysqldb
    - libmysqlclient-dev
  become: yes

- name: Copy custom index file to default webapp
  template: src=mysqld.cnf dest=/etc/mysql/mysql.conf.d/mysqld.cnf


- name: update mysql root password for all root accounts
  mysql_user:
    login_password: password
    name: root
    password: password
    priv: '*.*:ALL'
    host: '%'


- name: create a new database
  mysql_db:
    name: test
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: add sample data to database
  copy: src=dump.sql dest=/tmp/dump.sql


- name: insert sample data into database
  mysql_db:
    name: test
    state: import
    target: /tmp/dump.sql
    login_user: root
    login_password: "{{ mysql_root_password }}"
  notify: restart mysql

- name: restart mysql
  service: name=mysql state=restarted