---
- name: Create security groups
  local_action:
    module: ec2_group
    name: "{{ service_name }}-sec"
    description: "Ansible Security Group"
    region: "{{region}}"
    vpc_id: "{{ vpc_id }}"
    rules: "{{ security_rules }}"

#    - proto: tcp
#      from_port: "{{ item }}"
#      to_port: "{{ item }}"
#      cidr_ip: 0.0.0.0/0
#    with_items: "{{ service_port }}"

- name: Launch instances
  local_action:
    module: ec2
    key_name: "{{ keypair }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    region: "{{region}}"
    wait: yes
    group: "{{ service_name }}-sec"
    count_tag:
      Group: "{{ tag_ec2_group }}"
    exact_count: "{{ instances_to_lauch }}"
    instance_tags:
       Name: "{{ tag_ec2_name }}"
       Group: "{{ tag_ec2_group }}"
       Current: "{{ tag_ec2_current }}"
  register: ec2

- name: dispaly var
  debug: var=ec2

- name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
  add_host:
    hostname: "{{ item.public_ip }}"
    groups: "{{ service_group }}"
  with_items: "{{ ec2.instances }}"



- name: Wait for SSH to come up
  local_action: wait_for
                host={{ item.public_dns_name }}
                port=22
                state=started
  with_items: "{{ ec2.instances }}"




